### PR TITLE
fix: install docker-ce and docker-ce-cli v19.03.15 for ubuntu

### PR DESCRIPTION
**Pull request by jimil749**
Issue: #1 

Signed-off-by: Jimil Desai <jimildesai42@gmail.com>

### CODE REVIEW

**Comment by ebocchi** [comment]
We also need containerd:
```
root@79573b7401e5:/# dpkg --install docker-ce_20.10.9~3-0~ubuntu-focal_amd64.deb  docker-ce-cli_20.10.9~3-0~ubuntu-focal_amd64.deb 
(Reading database ... 4778 files and directories currently installed.)
Preparing to unpack docker-ce_20.10.9~3-0~ubuntu-focal_amd64.deb ...
Unpacking docker-ce (5:20.10.9~3-0~ubuntu-focal) over (5:20.10.9~3-0~ubuntu-focal) ...
Selecting previously unselected package docker-ce-cli.
Preparing to unpack docker-ce-cli_20.10.9~3-0~ubuntu-focal_amd64.deb ...
Unpacking docker-ce-cli (5:20.10.9~3-0~ubuntu-focal) ...
dpkg: dependency problems prevent configuration of docker-ce:
 docker-ce depends on containerd.io (>= 1.4.1); however:
  Package containerd.io is not installed.
```

Looking how to install all of them together

**Comment by jimil749** [comment]
@ebocchi I've added the containerd installation in the script for ubuntu. Works fine! 

Should we also update the containerd version to latest?

**Comment by ebocchi** [comment]
I still had dependency problems and fixed by installing the 3 packages in a single run. See the commit above.
The update of containerd is added to the other PR (https://github.com/sciencebox/mboxed/pull/3/commits/e134ddfd9db881aece3b9e0ffe9405c1172537c4)

**Comment by ebocchi** [comment]
I am merging to devel...

**Pull request merged**
