### PR TITLE
update helm, k8s, docker and minikube versions

### PR DESCRIPTION
**Pull request by ebocchi**
Signed-off-by: Jimil Desai <jimildesai42@gmail.com>

### CODE REVIEW

**Comment by ebocchi** [comment]
BTW, this is breaking Ubuntu deployment for now. Will review https://github.com/sciencebox/mboxed/pull/2 and rebase accordingly

**Comment by ebocchi** [comment]
> BTW, this is breaking Ubuntu deployment for now. Will review #2 and rebase accordingly

Fixed by rebasing.

**Comment by jimil749** [comment]
@ebocchi did you try to install on CENTOS?

**Comment by ebocchi** [comment]
> @ebocchi did you try to install on CENTOS?

No fully, yes. I am building a VM.
I am also noticing there are some other missing dependencies for the new docker version on CENTOS. Looking...

**Comment by ebocchi** [comment]
I am merging to devel

**Pull request merged**
